server:
  port: 18082

spring:
  application:
    name: deepdesk
  main:
    web-application-type: servlet
  codec:
      max-in-memory-size: 10MB
  ai:
    openai:
      api-key: ${WOKA_API_KEY}
      base-url: https://4.0.wokaai.com
      chat:
        enabled: true
        options:
          model: gpt-4o-mini
          max-completion-tokens: 6000
      embedding:
        enabled: true
        options:
          model: text-embedding-3-small
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        enabled: false
        options:
          model: claude-3-7-sonnet-20250219
          max-completion-tokens: 6000
    ollama:
      chat:
        enabled: false
        options:
          model: mistral
      embedding:
        enabled: false
        options:
          model: nomic-embed-text
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
        sse:
          connections:
            code-filesystem:
              url: http://0.0.0.0:38085
    vectorstore:
      chroma:
        initialize-schema: true
        collection-name: deepdesk

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
    com.moguyn.deepdesk: DEBUG

core:
  llm:
    prompt:
      system: |
        - 你是洗车行业的企业级AI助手, 你的任务是回答用户关于洗车行业的相关问题。
        - 禁止提供任何威胁安全与隐私的信息，例如密码，密钥，身份证号，银行卡号等。
        - 实用工具出错时, 请修正工具的输入参数，并重试。
        - 如果尝试修正多次后仍然出错，可以尝试搜索互联网上的相关信息。
        - 通过访问数据库, 你可以获得企业内部有关洗车业务的信息, 这是一个mysql数据库。数据库中包含下面这些业务数据表
          - 客户表: customer
          - 洗车订单表: wash_order
          - 洗车API调用日志: order_wash_log
          - 洗车站点表: car_wash
          - 访问数据库时，请先通过元数据获得表中包含的字段名称和类型。
          - 每次访问的数据不得超过300条记录。你可以通过分页查询来获取更多的数据。
        - 通过搜索工具，你可以搜索互联网上的有关洗车行业的信息。
        - 输出请只使用中文, 并一律使用markdown格式。
        - 如果有文件访问需要，请先确认允许访问的文件路径。所有文件访问请使用绝对路径。
    max-tokens: 20000
    history-window-size: 10

  ui:
    type: web

  mcp:
    roots: "."

  advisors:
    chat-memory-advisor-enabled: true
