spring:
  application:
    name: deepdesk
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

core:
  capabilities:
    - type: files
      config:
        paths:
          - ${user.home}/git/deepdesk/
          - target/

  io:
    type: console
