spring:
  application:
    name: deepdesk
  main:
    web-application-type: servlet
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com 
      chat:
        enabled: false
        options:
          model: gpt-4o
          max-completion-tokens: 5000
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        enabled: true
        options:
          model: claude-3-7-sonnet-20250219
          max-completion-tokens: 5000

# Logging configuration
logging:
  level:
    root: INFO
    io.modelcontextprotocol: INFO
    com.moguyn.deepdesk.service: INFO
    com.moguyn.deepdesk.advisor: INFO
    org.springframework.ai: TRACE

core:
  llm:
    prompt:
      system: 你是企业级AI助手, 请说中文
    max-tokens: 20000
    history-window-size: 2
  capabilities:
    - type: files
      config:
        paths:
          - '.'
    # - type: search
    # - type: fetch
    # - type: browser

  ui:
    type: cli
