server:
  port: 18082

spring:
  application:
    name: deepdesk
  main:
    web-application-type: servlet
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        enabled: true
        options:
          model: gpt-4o-mini
          max-completion-tokens: 6000
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        enabled: false
        options:
          model: claude-3-7-sonnet-20250219
          max-completion-tokens: 6000
    ollama:
      chat:
        enabled: false
        options:
          model: mistral
    mcp:
      client:
        type: ASYNC
        stdio:
          servers-configuration: classpath:mcp-servers.json

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG

core:
  llm:
    prompt:
      system: 你是企业级AI助手, 请说中文, 请使用markdown格式输出
    max-tokens: 20000
    history-window-size: 5

  ui:
    type: web
