spring:
  application:
    name: deepdesk
  main:
    web-application-type: servlet
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        enabled: true
        options:
          model: deepseek-chat
          max-completion-tokens: 6000
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        enabled: false
        options:
          model: claude-3-7-sonnet-20250219
          max-completion-tokens: 6000
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json

# Logging configuration
logging:
  level:
    root: INFO
    io.modelcontextprotocol: INFO
    com.moguyn.deepdesk.service: INFO
    com.moguyn.deepdesk.advisor: INFO
    org.springframework.ai: DEBUG

core:
  llm:
    prompt:
      system: 你是企业级AI助手, 请说中文
    max-tokens: 20000
    history-window-size: 5

  ui:
    type: cli
