server:
  port: 18082

spring:
  application:
    name: deepdesk
  main:
    web-application-type: servlet
  codec:
      max-in-memory-size: 10MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        enabled: true
        options:
          model: gpt-4o-mini
          max-completion-tokens: 6000
      embedding:
        enabled: true
        options:
          model: text-embedding-3-small
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        enabled: false
        options:
          model: claude-3-7-sonnet-20250219
          max-completion-tokens: 6000
    ollama:
      chat:
        enabled: false
        options:
          model: mistral
      embedding:
        enabled: false
        options:
          model: nomic-embed-text
    mcp:
      client:
        type: ASYNC
        stdio:
          servers-configuration: classpath:mcp-servers.json
        sse:
          connections:
            code-filesystem:
              url: http://0.0.0.0:38085
    vectorstore:
      chroma:
        initialize-schema: true
        collection-name: deepdesk

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
    com.moguyn.deepdesk: DEBUG

core:
  llm:
    prompt:
      system: |
        - 你是企业级AI助手, 请只说中文, 使用markdown格式输出。
        - 如果有文件访问需要，请先确认允许访问的文件路径。所有文件访问请使用绝对路径。
    max-tokens: 20000
    history-window-size: 5

  ui:
    type: web

  mcp:
    roots: "."

  advisors:
    chat-memory-advisor-enabled: true
