server:
  port: 18082

spring:
  application:
    name: deepdesk
  main:
    web-application-type: servlet
  codec:
      max-in-memory-size: 10MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com
      chat:
        enabled: true
        options:
          model: gpt-4o-mini
          max-completion-tokens: 6000
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        enabled: false
        options:
          model: claude-3-7-sonnet-20250219
          max-completion-tokens: 6000
    ollama:
      chat:
        enabled: false
        options:
          model: mistral
    mcp:
      client:
        type: ASYNC
        stdio:
          servers-configuration: classpath:mcp-servers.json
        sse:
          connections:
            code-filesystem:
              url: http://0.0.0.0:38085

logging:
  level:
    root: INFO
    org.springframework.ai: DEBUG
    com.moguyn.deepdesk: DEBUG

core:
  llm:
    prompt:
      system: 你是企业级AI助手, 请只说中文, 使用markdown格式输出。
    max-tokens: 20000
    history-window-size: 5

  ui:
    type: web
    
  advisors:
    plan-advisor-enabled: true
    next-step-advisor-enabled: true
    critical-thinker-enabled: true
    chat-memory-advisor-enabled: true
