spring:
  application:
    name: deepdesk
  main:
    web-application-type: servlet
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}

# Logging configuration
logging:
  level:
    root: INFO
    io.modelcontextprotocol: INFO

core:
  capabilities:
    - type: files
      config:
        paths:
          - ${user.home}
    - type: search
    - type: fetch
    - type: browser

  ui:
    type: web
