spring:
  application:
    name: deepdesk
  main:
    web-application-type: none
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}

core:
  llm:
    prompt:
      system: 你是企业级AI助手, 请说中文
  capabilities:
    - type: files
      config:
        paths:
          - ${user.home}/git/deepdesk/
          - ./target/
    - type: search

  ui:
    type: cli
