services:
  deepdesk:
    image: verrerie/deepdesk:latest
    ports:
      - 18082:8080
    environment:
      - WOKA_API_KEY=your_woka_api_key
      - BOCHAT_API_KEY=your_bocchat_api_key
    volumes:
      - ./deepdesk:/config
  filesystem:
    image: verrerie/filesystem-go:latest
    ports:
      - 38085:38085
    volumes:
      - ./filesystem:/projects
  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.20
    ports:
      - 8000:8000
    environment:
      - CHROMA_API_IMPL=rest
      - CHROMA_HOST=0.0.0.0
      - CHROMA_PORT=8000
