POST http://localhost:18082/openai/chat/completions
Content-Type: application/json

{
    "messages": [{"role": "user", "content": "总结 CHANGELOG.md 文件"}],
    "stream": false
}

### not working yet
POST http://localhost:18082/openai/chat/completions
Accept: text/event-stream
Content-Type: application/json
Cache-Control: no-cache
Connection: keep-alive

{
    "messages": [{"role": "user", "content": "总结 CHANGELOG.md 文件"}],
    "stream": true
}

###
GET https://api.anthropic.com/v1/models
x-api-key: {{$processEnv ANTHROPIC_API_KEY}}
anthropic-version: 2023-06-01