on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: java
          release-name-format: "v${{ version }}"
          release-notes-format: "changelog"
          release-notes-file: "CHANGELOG.md"
          release-notes-start-tag: "v0.0.1"
          release-notes-end-tag: "v${{ version }}"
