on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  lint-pr-title:
    name: Validate PR title
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: build-native-executables
    if: github.ref_name == 'main'
    steps:
      - name: Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: maven

      - name: Build Native Executables
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/workflows/native-builds.yml

      - name: Upload Release Artifact
        needs: build-native-executables
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} ./target/deepdesk-*
          gh release upload ${{ steps.release.outputs.tag_name }} ./CHANGELOG.md
          gh release upload ${{ steps.release.outputs.tag_name }} ./LICENSE
