on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  lint-pr-title:
    name: Validate PR title
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  release-code:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    name: Release Code
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: maven

  release-native-executables:
    needs: release-code
    name: Release Native Executables
    if: ${{ needs.release-code.outputs.release_created }}
    uses: ./.github/workflows/release-native-builds.yml
